routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::redirect('/', 'login');

Route::middleware('auth')->group(function() {
    Route::get('/home', function () {
        return view('welcome');
    })->name('home');

    Route::get('/sub-district', \App\Http\Controllers\SubDistrictController::class)->name('subdistrict.index');
    Route::resource('/category', \App\Http\Controllers\CategoryController::class);
    Route::resource('/place', \App\Http\Controllers\PlaceController::class);
    Route::resource('/place/{place}/menu', \App\Http\Controllers\PlaceMenuController::class)->scoped();
});

app/Models/Place.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Place extends Model
{
    use HasFactory;

    public function getImageUrlAttribute()
    {
        if ($this->image) {
            return asset($this->image);
        }

        return null;
    }

    public function scopeSearchPlace($query, $keyword)
    {
        return $query->where('name', 'like', '%' . $keyword . '%')
            ->orWhere('description', 'like', '%' . $keyword . '%')
            ->orWhere('address', 'like', '%' . $keyword . '%')
            ->orWhere('phone', 'like', '%' . $keyword . '%')
            ->orWhereHas('subDistrict', function ($query) use ($keyword) {
                $query->where('name', 'like', '%' . $keyword . '%');
            });
    }

    public function subDistrict()
    {
        return $this->belongsTo(SubDistrict::class);
    }

    public function menus()
    {
        return $this->hasMany(Menu::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class);
    }
}

app/Http/Controllers/Api/Place/ListPlaceController.php
<?php

namespace App\Http\Controllers\Api\Place;

use App\Http\Controllers\Controller;
use App\Http\Resources\PlaceResource;
use App\Models\Place;
use Illuminate\Http\Request;

class ListPlaceController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $places = Place::query();

        if ($request->has('keyword')) {
            $places->searchPlace($request->keyword);
        }

        return PlaceResource::collection($places->paginate(5));
    }
}

app/Http/Controllers/Api/Place/RelatedPlaceController.php
<?php

namespace App\Http\Controllers\Api\Place;

use App\Http\Controllers\Controller;
use App\Http\Resources\PlaceResource;
use App\Models\Place;
use Illuminate\Http\Request;

class RelatedPlaceController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request, Place $place)
    {
        $relatedPlaces = $place->subDistrict->places()
            ->where('id', '!=', $place->id)
            ->inRandomOrder()
            ->get()
            ->take(config('kuliner.related_place_limit'));

        return PlaceResource::collection($relatedPlaces);
    }
}

app/Http/Controllers/Api/Place/SearchPlaceController.php
<?php

namespace App\Http\Controllers\Api\Place;

use App\Http\Controllers\Controller;
use App\Http\Resources\PlaceResource;
use App\Models\Place;
use Illuminate\Http\Request;

class SearchPlaceController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request)
    {
        $places = Place::searchPlace($request->keyword)
            ->paginate(5);

        return PlaceResource::collection($places);
    }
}

app/Http/Controllers/Api/Place/ShowPlaceController.php
<?php

namespace App\Http\Controllers\Api\Place;

use App\Http\Controllers\Controller;
use App\Http\Resources\PlaceResource;
use App\Models\Place;
use Illuminate\Http\Request;

class ShowPlaceController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function __invoke(Request $request, Place $place)
    {
        return new PlaceResource($place);
    }
}

app/Http/Controllers/PlaceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Place;
use App\Models\SubDistrict;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Yajra\DataTables\DataTables;

class PlaceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $places = Place::with('subDistrict');

            return DataTables::of($places)
                ->addIndexColumn()
                ->addColumn('subDistrictName', function (Place $place) {
                    return $place->subDistrict->name;
                })
                ->addColumn('place-menu', 'places.place-link')
                ->addColumn('action', 'places.dt-action')
                ->rawColumns(['place-menu', 'action'])
                ->toJson();
        }

        return view('places.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('places.create', [
            'subDistricts' => SubDistrict::get(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => ['required'],
            'description' => ['required'],
            'address' => ['required'],
            'phone' => ['required', 'numeric'],
            'image' => ['required', 'image'],
            'latitude' => ['required'],
            'longitude' => ['required']
        ]);

        $image = null;

        if ($request->has('image')) {
            $image = $request->file('image')->store('images');
        }

        Place::create([
            'sub_district_id' => $request->sub_district_id,
            'name' => $request->name,
            'description' => $request->description,
            'address' => $request->address,
            'phone' => $request->phone,
            'image' => $image,
            'latitude' => $request->latitude,
            'longitude' => $request->longitude
        ]);

        session()->flash('success', 'Berhasil tambah data tempat kuliner');

        return redirect()->route('place.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Place $place)
    {
        return view('places.edit', [
            'subDistricts' => SubDistrict::get(),
            'place' => $place
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Place $place)
    {
        $this->validate($request, [
            'name' => ['required'],
            'description' => ['required'],
            'address' => ['required'],
            'phone' => ['required', 'numeric'],
            'latitude' => ['required'],
            'longitude' => ['required']
        ]);

        $image = $place->image;

        if ($request->has('image')) {
            if (Storage::exists($place->image)) {
               Storage::delete($place->image);
            }

            $image = $request->file('image')->store('images');
        }

        $place->update([
            'sub_district_id' => $request->sub_district_id,
            'name' => $request->name,
            'description' => $request->description,
            'address' => $request->address,
            'phone' => $request->phone,
            'image' => $image,
            'latitude' => $request->latitude,
            'longitude' => $request->longitude
        ]);

        session()->flash('success', 'Berhasil perbarui data tempat kuliner');

        return redirect()->route('place.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Place $place)
    {
        if ($place->delete()) {
            session()->flash('error', 'Data dihapus');

            return response()->json([
                'success' => true,
            ]);
        }

        return response()->json([
            'success' => false,
        ]);
    }
}

resources/views/places/create.blade.php
<x-templates.default>
    <x-slot name="title">Tambah Tempat Kuliner</x-slot>

    <form action="{{ route('place.store') }}" class="card" method="post" enctype="multipart/form-data">
        @csrf
        <div class="card-header">
            <h1 class="card-title">Tambah Data Tempat Kuliner</h1>
        </div>

        <div class="card-body">
            <div class="form-group">
                <label for="">Nama</label>
                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                    placeholder="Masukkan nama tempat kuliner" value="{{ old('name') }}">

                @error('name')
                    <span class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group mt-2">
                <label for="">Deskripsi</label>
                <textarea name="description" id="" rows="3"
                    class="form-control @error('description') is-invalid @enderror"
                    placeholder="Deskripsi tempat kuliner">{{ old('description') }}</textarea>

                @error('description')
                    <span class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group mt-2">
                <label for="">Kecamatan</label>
                <select name="sub_district_id" id=""
                    class="form-control @error('sub_district_id') is-invalid @enderror">
                    @foreach ($subDistricts as $subDistrict)
                        <option value="{{ $subDistrict->id }}">{{ $subDistrict->name }}</option>
                    @endforeach
                </select>

                @error('sub_district_id')
                    <span class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group mt-2">
                <label for="">Alamat</label>
                <input type="text" name="address" class="form-control @error('address') is-invalid @enderror"
                    placeholder="Masukkan alamat tempat kuliner" value="{{ old('address') }}">

                @error('address')
                    <span class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group mt-2">
                <label for="">Telepon</label>
                <input type="text" name="phone" class="form-control @error('phone') is-invalid @enderror"
                    placeholder="Masukkan no telepon tempat kuliner" value="{{ old('phone') }}">

                @error('phone')
                    <span class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group mt-2">
                <label for="">Foto</label>
                <input type="file" name="image" class="form-control @error('image') is-invalid @enderror"
                    placeholder="Masukkan no telepon tempat kuliner" value="{{ old('image') }}">

                @error('image')
                    <span class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group mt-2">
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div id="map"></div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <label for="">Latitude</label>
                        <input type="text" name="latitude" id="latitude"
                            class="form-control @error('latitude') is-invalid @enderror"
                            placeholder="Masukkan no telepon tempat kuliner" value="{{ old('latitude') }}" readonly>

                        @error('latitude')
                            <span class="invalid-feedback">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="col-md-6 col-sm-12">
                        <label for="">Longitude</label>
                        <input type="text" name="longitude" id="longitude"
                            class="form-control @error('longitude') is-invalid @enderror"
                            placeholder="Masukkan no telepon tempat kuliner" value="{{ old('longitude') }}" readonly>

                        @error('longitude')
                            <span class="invalid-feedback">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Simpan" class="btn btn-primary float-right">
        </div>
    </form>

    @push('extra-styles')
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
            integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
            crossorigin="" />
        <style>
            #map {
                height: 500px;
            }

        </style>
    @endpush

    @push('extra-scripts')
        <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
                integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
                crossorigin=""></script>

        <script>
            var map = L.map('map').fitWorld();

            L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
                attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
                maxZoom: 18,
                id: 'mapbox/streets-v11',
                tileSize: 512,
                zoomOffset: -1,
                accessToken: 'pk.eyJ1Ijoia2F3YW5rb2RpbmciLCJhIjoiY2t3cWg3aW1pMDY2MzJvbng5cWM5Y3V2aiJ9.3XUQum_yarzlylARjC3K-g'
            }).addTo(map);

            function onLocationFound(e) {
                var radius = e.accuracy;

                $('#latitude').val(e.latlng.lat)
                $('#longitude').val(e.latlng.lng)

                var locationMarker = L.marker(e.latlng, {
                    draggable: 'true'
                }).addTo(map);

                locationMarker.on('dragend', function(event) {
                    var marker = event.target;
                    var position = marker.getLatLng();

                    marker.setLatLng(position, {
                        draggable: 'true'
                    }).update()

                    $('#latitude').val(position.lat)
                    $('#longitude').val(position.lng)
                })
            }

            function onLocationError(e) {
                alert(e.message);
            }

            map.on('locationfound', onLocationFound);
            map.on('locationerror', onLocationError);
            map.locate({
                setView: true,
                maxZoom: 16
            });
        </script>
    @endpush
</x-templates.default>

resources/views/places/dt-action.blade.php
<a href="{{ route('place.edit', $model) }}" class="btn btn-warning">Edit</a>
<a href="#" class="btn btn-danger" id="delete" data-id="{{ $model->id }}">Hapus</a>

resources/views/places/edit.blade.php
<x-templates.default>
    <x-slot name="title">Perbarui Tempat Kuliner</x-slot>

    <form action="{{ route('place.update', $place) }}" class="card" method="post"
        enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <div class="card-header">
            <h1 class="card-title">Perbarui Data Tempat Kuliner</h1>
        </div>

        <div class="card-body">
            <div class="form-group">
                <label for="">Nama</label>
                <input type="text" name="name" class="form-control @error('name') is-invalid @enderror"
                    placeholder="Masukkan nama tempat kuliner" value="{{ old('name') ?? $place->name }}">

                @error('name')
                    <span class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group mt-2">
                <label for="">Deskripsi</label>
                <textarea name="description" id="" rows="3"
                    class="form-control @error('description') is-invalid @enderror"
                    placeholder="Deskripsi tempat kuliner">{{ old('description') ?? $place->description }}</textarea>

                @error('description')
                    <span class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group mt-2">
                <label for="">Kecamatan</label>
                <select name="sub_district_id" id=""
                    class="form-control @error('sub_district_id') is-invalid @enderror">
                    @foreach ($subDistricts as $subDistrict)
                        <option value="{{ $subDistrict->id }}" @if ($subDistrict->id == $place->sub_district_id) selected @endif>{{ $subDistrict->name }}
                        </option>
                    @endforeach
                </select>

                @error('sub_district_id')
                    <span class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group mt-2">
                <label for="">Alamat</label>
                <input type="text" name="address" class="form-control @error('address') is-invalid @enderror"
                    placeholder="Masukkan alamat tempat kuliner" value="{{ old('address') ?? $place->address }}">

                @error('address')
                    <span class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group mt-2">
                <label for="">Telepon</label>
                <input type="text" name="phone" class="form-control @error('phone') is-invalid @enderror"
                    placeholder="Masukkan no telepon tempat kuliner" value="{{ old('phone') ?? $place->phone }}">

                @error('phone')
                    <span class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group mt-2">
                <label for="">Foto</label>
                <input type="file" name="image" class="form-control @error('image') is-invalid @enderror"
                    placeholder="Masukkan no telepon tempat kuliner" value="{{ old('image') }}">

                @error('image')
                    <span class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>

            <div class="form-group mt-2">
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <div id="map"></div>
                    </div>
                    <div class="col-md-6 col-sm-12">
                        <label for="">Latitude</label>
                        <input type="text" name="latitude" id="latitude"
                            class="form-control @error('latitude') is-invalid @enderror"
                            placeholder="Masukkan no telepon tempat kuliner"
                            value="{{ old('latitude') ?? $place->latitude }}" readonly>

                        @error('latitude')
                            <span class="invalid-feedback">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    <div class="col-md-6 col-sm-12">
                        <label for="">Longitude</label>
                        <input type="text" name="longitude" id="longitude"
                            class="form-control @error('longitude') is-invalid @enderror"
                            placeholder="Masukkan no telepon tempat kuliner"
                            value="{{ old('longitude') ?? $place->longitude }}" readonly>

                        @error('longitude')
                            <span class="invalid-feedback">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <input type="submit" value="Simpan" class="btn btn-primary float-right">
        </div>
    </form>

    @push('extra-styles')
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
            integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
            crossorigin="" />
        <style>
            #map {
                height: 500px;
            }
        </style>
    @endpush

    @push('extra-scripts')
        <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
                integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
                crossorigin=""></script>

        <script>
            var map = L.map('map').setView([{{ $place->latitude }}, {{ $place->longitude }}], 16);

            L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}', {
                attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
                maxZoom: 18,
                id: 'mapbox/streets-v11',
                tileSize: 512,
                zoomOffset: -1,
                accessToken: 'pk.eyJ1Ijoia2F3YW5rb2RpbmciLCJhIjoiY2t3cWg3aW1pMDY2MzJvbng5cWM5Y3V2aiJ9.3XUQum_yarzlylARjC3K-g'
            }).addTo(map);

            var marker = L.marker([{{ $place->latitude }}, {{ $place->longitude }}], {
                draggable: 'true'
            }).addTo(map);

            marker.on('dragend', function(event) {
                var marker = event.target;
                var position = marker.getLatLng();

                marker.setLatLng(position, {
                    draggable: 'true'
                }).update()

                $('#latitude').val(position.lat)
                $('#longitude').val(position.lng)
            })

            function onLocationError(e) {
                alert(e.message);
            }
        </script>
    @endpush
</x-templates.default>

resources/views/places/index.blade.php
<x-templates.default>
    <x-slot name="title">Data Tempat Kuliner</x-slot>

    <div class="card">
        <div class="card-header">
            <a href="{{ route('place.create') }}" class="btn btn-primary">Tambah Data</a>
        </div>

        <div class="card-body">
            <table class="table table-striped" id="dataTable">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nama</th>
                        <th>Kecamatan</th>
                        <th>Deskripsi</th>
                        <th>Alamat</th>
                        <th>Telepon</th>
                        <th>Tindakan</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>

        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="modalLabel">Hapus Data</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        Apakah kamu yakin menghapus data ini?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Batalkan</button>
                        <button type="button" class="btn btn-danger" data-id="" id="confirmDelete">Hapus</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @push('extra-styles')
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.11.3/datatables.min.css" />
    @endpush

    @push('extra-scripts')
        <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.11.3/datatables.min.js"></script>

        <script>
            $(function() {
                $('#dataTable').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: '{!! route('place.index') !!}',
                    columns: [{
                            data: 'DT_RowIndex',
                            name: 'DT_RowIndex',
                            orderable: false
                        },
                        {
                            data: 'place-menu',
                            name: 'place-menu'
                        },
                        {
                            data: 'subDistrictName',
                            name: 'subDistrictName'
                        },
                        {
                            data: 'description',
                            name: 'description'
                        },
                        {
                            data: 'address',
                            name: 'address'
                        },
                        {
                            data: 'phone',
                            name: 'phone'
                        },
                        {
                            data: 'action',
                            name: 'action'
                        }
                    ]
                });
            });

            $('#dataTable').on('click', 'a#delete', function(e) {
                e.preventDefault()
                var id = $(this).data('id')
                $('#confirmDelete').attr('data-id', id)
                $('#deleteModal').modal('show')
            })

            $('#confirmDelete').click(function(e) {
                e.preventDefault()
                var id = $(this).data('id')

                $.ajax({
                    type: 'DELETE',
                    url: '/place/' + id,
                    data: {
                        '_token': "{{ csrf_token() }}"
                    },
                    success: function(response) {
                        if (response.success) {
                            window.location.href = ''
                        }
                    },
                })
            })
        </script>
    @endpush
</x-templates.default>

resources/views/places/place-link.blade.php
<a href="{{ route('menu.index', $model->id) }}">{{ $model->name }}</a>